# SPDX-FileCopyrightText: 2021 - 2023 Mewbot Developers <mewbot@quicksilver.london>
#
# SPDX-License-Identifier: BSD-2-Clause

name: Publish to Test PyPI

on:
  - push

jobs:
  publish:
    name: Publish Packages
    runs-on: ubuntu-latest

    if: always()

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python ${{ vars.DEFAULT_PYTHON }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ vars.DEFAULT_PYTHON }}
          cache: pip
          cache-dependency-path: |
            requirements.txt

      - name: Install dependencies
        run: pip install build --user

      - name: Build a binary wheel and a source tarball
        run: python -m build --sdist --wheel --outdir dist/
        env:
          RELEASE_VERSION: "0.dev${{ github.run_id }}"

      - name: Archive installation artifacts
        uses: actions/upload-artifact@v4
        with:
          name: builds
          path: dist

      - name: Publish distribution packages to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TEST_API_KEY }}
          repository-url: https://test.pypi.org/legacy/
